syntax = "proto3";

package rl4phys;

// B1: energy deposit per step
message EventScoring
{
    float edep = 1;
}

// MUonE: one step inside volume
message StepHit
{
    float x = 1;
    float y = 2;
    float z = 3;
    float px = 4;
    float py = 5;
    float pz = 6;
    float e_kin = 7;
}

//Oneof types defined in payload
message Data
{
    oneof payload
    {
        EventScoring event_scoring = 1;
        StepHit step_hit = 2;
    }
}

message Reply {}

service SendService
{
    rpc SendData (Data) returns (Reply) {}
}
