# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rl4phy.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rl4phy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crl4phy.proto\x12\x07rl4phys\".\n\x0c\x45ventScoring\x12\x0c\n\x04\x65\x64\x65p\x18\x01 \x01(\x02\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\x05\"\xa1\x01\n\x07StepHit\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\n\n\x02px\x18\x04 \x01(\x02\x12\n\n\x02py\x18\x05 \x01(\x02\x12\n\n\x02pz\x18\x06 \x01(\x02\x12\r\n\x05\x65_kin\x18\x07 \x01(\x02\x12\x10\n\x08track_id\x18\x08 \x01(\x05\x12\x10\n\x08\x65vent_id\x18\t \x01(\x05\x12\x11\n\tparent_id\x18\n \x01(\x05\x12\x0b\n\x03pdg\x18\x0b \x01(\x05\"z\n\x07\x42\x35\x45vent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\x05\x12\x1a\n\x12\x64rift_chamber_hits\x18\x02 \x03(\x05\x12\x16\n\x0ehodoscope_time\x18\x03 \x03(\x02\x12\x13\n\x0b\x65m_cal_edep\x18\x04 \x03(\x02\x12\x14\n\x0chad_cal_edep\x18\x05 \x03(\x02\"\x8c\x01\n\nTrajectory\x12\x10\n\x08track_id\x18\x01 \x01(\x05\x12\x11\n\tparent_id\x18\x02 \x01(\x05\x12\x0b\n\x03pdg\x18\x03 \x01(\x05\x12\x0e\n\x06\x63harge\x18\x04 \x01(\x02\x12\x15\n\rparticle_name\x18\x05 \x01(\t\x12\x0e\n\x06points\x18\x06 \x03(\x02\x12\x15\n\rinitial_e_kin\x18\x07 \x01(\x02\"P\n\x11\x45ventTrajectories\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\x05\x12)\n\x0ctrajectories\x18\x02 \x03(\x0b\x32\x13.rl4phys.Trajectory\"\xc7\x01\n\x04\x44\x61ta\x12.\n\revent_scoring\x18\x01 \x01(\x0b\x32\x15.rl4phys.EventScoringH\x00\x12$\n\x08step_hit\x18\x02 \x01(\x0b\x32\x10.rl4phys.StepHitH\x00\x12$\n\x08\x62\x35_event\x18\x03 \x01(\x0b\x32\x10.rl4phys.B5EventH\x00\x12\x38\n\x12\x65vent_trajectories\x18\x04 \x01(\x0b\x32\x1a.rl4phys.EventTrajectoriesH\x00\x42\t\n\x07payload\"\x07\n\x05Reply\"\x1c\n\x0cGeometryFile\x12\x0c\n\x04gdml\x18\x01 \x01(\x0c\x32s\n\x0bSendService\x12+\n\x08SendData\x12\r.rl4phys.Data\x1a\x0e.rl4phys.Reply\"\x00\x12\x37\n\x0cSendGeometry\x12\x15.rl4phys.GeometryFile\x1a\x0e.rl4phys.Reply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rl4phy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTSCORING']._serialized_start=25
  _globals['_EVENTSCORING']._serialized_end=71
  _globals['_STEPHIT']._serialized_start=74
  _globals['_STEPHIT']._serialized_end=235
  _globals['_B5EVENT']._serialized_start=237
  _globals['_B5EVENT']._serialized_end=359
  _globals['_TRAJECTORY']._serialized_start=362
  _globals['_TRAJECTORY']._serialized_end=502
  _globals['_EVENTTRAJECTORIES']._serialized_start=504
  _globals['_EVENTTRAJECTORIES']._serialized_end=584
  _globals['_DATA']._serialized_start=587
  _globals['_DATA']._serialized_end=786
  _globals['_REPLY']._serialized_start=788
  _globals['_REPLY']._serialized_end=795
  _globals['_GEOMETRYFILE']._serialized_start=797
  _globals['_GEOMETRYFILE']._serialized_end=825
  _globals['_SENDSERVICE']._serialized_start=827
  _globals['_SENDSERVICE']._serialized_end=942
# @@protoc_insertion_point(module_scope)
